// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nscuvpjylxitrvkkqpoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zY3V2cGp5bHhpdHJ2a2txcG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjg1MjEsImV4cCI6MjA1ODYwNDUyMX0.mR9r1iB1MYPumWti5CdyApf7F3crzQ414UrXmts-yKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);